Repository nilssonf/PROJECT_FAR, pull requests merged in 2022-12, with the labels that each got.

#22 static JSON files updated with content
  php/topDrinks.json
  php/topIngredients.json
Labels: good first issue

#24 editUser.php
  php/createUser.php
  php/editUser.php
  php/users.json
Labels: good first issue

#28 log in handling (logIn.php)
  php/logIn.php
  php/users.json
Labels: good first issue

#30 To-do:s
  php/createUser.php
  php/editUser.php
  php/logIn.php
Labels: good first issue

#31 create comment handling
  php/comments.json
  php/createComment.php
Labels: good first issue

#32 handling for editComment.php
  php/comments.json
  php/editComment.php
Labels: good first issue

#33 handling for deleteComment.php
  php/comments.json
  php/deleteComment.php
Labels: good first issue

#39 Fixed to do notes
  php/addFavorites.php
  php/createUser.php
  php/deleteComment.php
  php/deleteFavorites.php
  php/editUser.php
  php/functions.php
  php/logIn.php
  php/topDrinks.json
  php/users.json
Labels: good first issue

#40 added folder and two fonts
  fonts/MinyaOutlineDemo-VGRjx.otf
  fonts/TiemposHeadline-Regular.otf
  fonts/TiemposHeadline-RegularItalic.otf
  fonts/TiemposHeadline-Semibold.otf
Labels: good first issue

#41 Created skelton for header, footer and startpage
  css/header.css
  css/styles.css
  html/index.html
  images/test.png
  js/footer.js
  js/header.js
Labels: good first issue

#42 Header, footer and startpage
  css/footer.css
  css/header.css
  css/startpage.css
  css/styles.css
  html/index.html
  html/search.html
  js/header.js
Labels: good first issue

#43 scroll fix
  css/styles.css
Labels: good first issue

#44 Menu changing based on loged in
  css/header.css
  html/index.html
  js/header.js
  js/index.js
Labels: good first issue

#45 photo + users.json fixes
  php/users.json
  profiles/new-moon.png
  profiles/standard_picture.png
Labels: good first issue

#46 header working
  css/header.css
  js/header.js
  php/users.json
  profiles/circle.png
Labels: enhancement

#53 Skeleton for favorites.html
  css/favorites.css
  html/favorites.html
  js/favorites.js
  js/header.js
Labels: good first issue

#54 Skeleton for search.html
  css/search.css
  html/search.html
  js/search.js
Labels: good first issue

#64 search JS
  css/search.css
  html/search.html
  js/search.js
Labels: good first issue

#65 small fix
  css/favorites.css
  html/favorites.html
  js/index.js
Labels: good first issue

#67 Filter drinks by searching name
  html/search.html
  js/search.js
Labels: good first issue

#71 Created select fields with options
  css/search.css
  html/search.html
  js/search.js
Labels: good first issue

#72 Filter drinks by alcohol, category and glass
  js/search.js
Labels: good first issue

#75 filter drinks by alcohol, category and glass based on Id
  js/search.js
Labels: good first issue

#76 filter by ingrediants
  html/search.html
  js/search.js
Labels: good first issue

#77 filter ingretiants in index.html
  html/index.html
  html/search.html
  js/index.js
  js/search.js
Labels: good first issue

#84 some fixes
  css/search.css
  css/startpage.css
  html/index.html
  html/search.html
  js/header.js
  js/index.js
  js/login.js
  js/search.js
Labels: good first issue

#87 checks for which user is logged in
  css/profile.css
  html/about.html
  html/favorites.html
  html/index.html
  html/profile.html
  html/search.html
  js/index.js
  js/login.js
  js/profile.js
  php/logIn.php
Labels: good first issue

#88 Login popUp
  css/header.css
  html/about.html
  js/header.js
  js/index.js
  js/login.js
Labels: good first issue

#89 added functionality
  js/header.js
  js/login.js
Labels: good first issue

#93 Create account pop up
  css/logIn.css
  html/about.html
  html/favorites.html
  html/index.html
  html/search.html
  js/login.js
Labels: good first issue

#94 login pop up display none when logged in
  js/header.js
  js/login.js
Labels: good first issue

#96 log in connects current user to profile
  html/profile.html
  js/header.js
  js/profile.js
Labels: enhancement

#102 all information about drinks in favorite drinks
  css/favorites.css
  js/favorites.js
  php/favorites.json
Labels: good first issue

#104 comments are now live
  css/profile.css
  html/profile.html
  js/header.js
  js/profile.js
  php/comments.json
Labels: enhancement

#105 drink links in comment
  css/profile.css
  js/profile.js
Labels: enhancement

#106 Create account
  css/favorites.css
  css/logIn.css
  js/login.js
  js/search.js
  php/favorites.json
  php/users.json
Labels: good first issue

#107 fixed issue with drink popups not opening
  js/popUp.js
  js/search.js
  php/favorites.json
Labels: fix

#108 random drink img from favorites.json
  css/search.css
  html/profile.html
  js/profile.js
  php/favorites.json
Labels: enhancement

#109 Added favicon (tab icon) to all pages
  html/index.html
  images/logo_bottled.png
  js/index.js
Labels: enhancement

#110 new (better sized) black heart for likes
  images/gillasvart.png
  php/favorites.json
Labels: enhancement, fix

#115 located to index.html when logged out
  css/popUp.css
  html/favorites.html
  js/favorites.js
  js/header.js
  js/index.js
  js/login.js
  js/search.js
  php/favorites.json
Labels: good first issue

#118 Ingredients are now level and centered
  css/header.css
  css/popUp.css
  js/popUp.js
Labels: fix

#119 added styling for clarity
  css/popUp.css
Labels: enhancement

#121 Not double header when creating account/log in
  js/header.js
Labels: good first issue

#122 startpage updated image (from api)
  css/startpage.css
  html/index.html
Labels: enhancement

#123 Update startpage.css
  css/startpage.css
Labels: enhancement

#126 Message if you search that does not exist
  css/search.css
  js/search.js
Labels: good first issue

#127 tags are compliant with figma
  css/search.css
Labels: enhancement

#128 message if you dont have any favorites drinks
  css/favorites.css
  html/favorites.html
  js/favorites.js
Labels: good first issue

#129 updates
  css/popUp.css
  js/popUp.js
Labels: enhancement

#132 small fixes
  js/favorites.js
  js/login.js
  js/search.js
  php/favorites.json
Labels: good first issue

#133 filter is sorted alphabetically
  css/favorites.css
  css/search.css
  html/search.html
  js/favorites.js
  js/login.js
  js/popUp.js
  js/search.js
Labels: good first issue

#134 small fix with select
  css/search.css
Labels: good first issue

#136 message if you dont have any favorites
  js/favorites.js
Labels: good first issue

#138 drink comments
  css/popUp.css
  js/popUp.js
  php/users.json
Labels: enhancement, good first issue

#139 small fixes to margins
  css/popUp.css
Labels: enhancement

#140 adding comments is now possible
  js/popUp.js
  php/comments.json
Labels: enhancement

#141 small fixes
  css/favorites.css
  css/search.css
  html/favorites.html
  html/search.html
  js/favorites.js
  js/popUp.js
  php/favorites.json
  php/users.json
Labels: good first issue

#142 message if you dont have any favorites in profile
  css/profile.css
  js/profile.js
  php/favorites.json
Labels: good first issue

#143 message if you dont have any comments in profile
  js/profile.js
  php/favorites.json
Labels: good first issue

#145 back to top btn
  css/search.css
  html/search.html
  images/up-arrow.png
  js/search.js
  php/users.json
Labels: enhancement

#147 Names on drinks and ingredients on firstpage
  css/startpage.css
  html/index.html
  js/index.js
Labels: good first issue

#148 log in pop up if you try to leave comment when you not are logged in
  css/popUp.css
  js/popUp.js
  php/comments.json
  php/favorites.json
Labels: good first issue

#149 tags are the same on favorites and search
  css/favorites.css
Labels: good first issue

#152 changing profile pic works now
  js/profile.js
  php/favorites.json
  php/users.json
  profiles/annaJ.jpeg
  profiles/anna_pommes.jpeg
Labels: enhancement

#153 fun hover transitions on top drinks and ings
  css/startpage.css
Labels: enhancement

#154 general styling fixes
  css/header.css
  css/search.css
Labels: enhancement

#155 error in comments.json fixed
  php/comments.json
Labels: fix

#156 Right src when you dont have any profilepic
  css/search.css
  js/header.js
  php/comments.json
  php/createUser.php
  php/users.json
Labels: good first issue

#157 style fixes to favorites
  css/favorites.css
  html/favorites.html
Labels: enhancement

#158 general style fixes
  css/about.css
  css/profile.css
  html/about.html
Labels: enhancement

#159 added clear btn
  css/search.css
  html/search.html
  js/search.js
Labels: enhancement

#160 bug fixed for input value on search
  js/search.js
Labels: fix

#161 favorites are clickable!
  css/favorites.css
  js/favorites.js
Labels: fix

#162 fixed search path
  js/profile.js
Labels: fix

#163 hover state effects on drinks
  css/favorites.css
  css/search.css
Labels: enhancement

#164 fixed popup styling and startpage hover
  css/popUp.css
  css/startpage.css
  js/popUp.js
Labels: fix

#172 updates search
  css/search.css
Labels: enhancement

#176 BUG FIX: fixed input field & alphabet on search
  css/search.css
Labels: fix

#183 unique name when saving profile picture
  js/profile.js
  php/addProfilePicture.php
  php/editUser.php
  php/users.json
  profiles/1672394390-dog03.jpg
Labels: good first issue

#190 comments delete and header fix on popup
  css/header.css
  css/popUp.css
  js/popUp.js
  php/comments.json
  php/favorites.json
Labels: enhancement

#191 comments are sorted by most recent
  js/popUp.js
Labels: enhancement

#192 Only 3 (latest) comments shown in profile
  js/profile.js
  php/comments.json
Labels: enhancement
